### ISSUE TITLE
RFC: Interface Templates for Datasources

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Helix.Docs#30]
Helix currently recommends the use of Interface Templates (in the Feature Layer) to construct Datasource Templates (in the Project Layer):
https://helix.sitecore.net/principles/templates/template-types.html#datasource-template

This makes the Datasource Template itself project-specific, and means that any new component requires defining at least two templates. The question has been raised as to whether this is premature architecture (YAGNI) for a typical Sitecore implementation.

Reasons for needing a separate project-level Datasource Template include:
* Use of an interface template means the Feature (rendering) itself can be unaware of whether the data is coming from the Page itself or a Datasource. (YAGNI?)
* Allows for configuration of site-specific standard values.
* Allows for configuration of site-specific workflows on Datasource templates.
  * Probably the most likely scenario. Though workflows on datasource items are currently confusing in the Sitecore UX, they are quite necessary at times.

The question is, **should Helix specifically call out use of Interface templates for Datasources as a conditional recommendation**, if the above scenarios are not requirements? Yes they could become requirements later, but is the refactoring effort that significant?

**Comment by jst-cyr** [comment]
My personal vote here is to always keep it simple. While there are certain cases where you might want to define another datasource template more specific to a site, often-times this is not the case and you just want to keep your architecture clean and simple (i.e. This Rendering Uses This Datasource Template).

Having a recommendation that outlines when the scenario could be helpful to do so seems like a better way to go rather than suggesting it be done every single time. 

Also, I'm not sure site-specific component datasource workflows are all that common? Typically it is the 'page' that goes through the workflow and expectation is that you make a way for the components to be 'approved' alongside it, so the component workflow itself is largely irrelevant in a lot of business user cases.

**Comment by AmitKumar-AK** [comment]
It's best to keep templates related to feature only in Feature layer because the purpose of Feature is to fulfill one of the requirement and it's not going to change on Project basis.
For example, in Insurance domain if you wanted to get quote specific to any policy the it's not going to change in other project.

**Comment by TwentyGotoTen** [comment]
In my experience, we generally know from day one if there are likely to be multiple sites that will end up sharing features. In those cases we generally follow the existing guidance which we find useful for site-specific standard values.
That said, I understand that following this approach 100% of the time can leave you with lots of useless extra templates. So maybe the guidance should be amended to present this pattern as the solution to a particular set of problems, not as something which should be followed for the sake of it.

**Comment by cassidydotdk** [comment]
Refactoring effort after the fact would be trivial. Given that any component should never care about the specific template is is being instantiated with (datasourced with) rather it should care only about it's known component template (what you call the feature template).

And there are much better ways of solving site specific standard values - beyond the scope of discussion here. But naming the requirement to double template mandatory would be a mistake, especially since you can never know up front if it will really be needed. YAGNI.

**Comment by derekcorreia** [comment]
I would agree that the reference of these always be project specific feels too rigid and sets up for more architecture for the sake of architecture than may be necessary. I think guidance akin to what @JensMikkelsen's second paragraph above feels the most correct to me. Hard to call it conditional guidance but establish that it's a pattern for creation of site specific datasource templates.

I'd have to be careful there and say that page templates are really datasource templates with more presentation, but I do agree those should only be in the project layer. Not the subject of this RFC though :)

**Comment by dugardeynh** [comment]
I'm okay with the idea of having DataSource templates inheriting Interface templates. I see added value in having the option to define site-specific standard values. It's not that big an effort to create an extra template that offers you this functionality.
The big downside to this idea is that a default Sitecore installation doesn't allow you to implement this principle. On https://helix.sitecore.net/principles/layout/datasource-settings.html you already get two reasons why it's hard. The documentation does mention a proposed solution in Habitat but I don't think it's up to every implementer to implement and maintain this on his own project. 
These are two known difficulties with the Interface and DataSource templates idea. There might be other places as well e.g. when you want to use Sitecore Query.

**Comment by nickwesselman** [comment]
Alternate, simplified structure implemented in #46
